### ISSUE TITLE
checksum genesis file

### ISSUE THREAD

**Issue by PietroAnsidei** [desmos-labs/docs#16]
In [https://docs.desmos.network/fullnode/setup#3-get-the-genesis-file](https://docs.desmos.network/fullnode/setup#3-get-the-genesis-file) , when the user is required to verify the checksum of the downloaded file, the filepath is relative, while the file has been downloaded in ~/.desmos/config/genesis.json. Please correct the line of code into:

jq -S -c -M '' /root/.desmos/config/genesis.json | shasum -a 256

**Comment by bragaz** [comment]
@PietroAnsidei Thanks! Fixed
